### ISSUE TITLE
cannot figure out how to connect google sheet

### ISSUE THREAD

**Issue by nickmerl** [nickmerl/database_practice#1]
currently it says that I have authentication but nothing happens when you create input the data in the app.

**Comment by nickmerl** [comment]
I honestly don't have a good understanding of the issue and why things are not working so can't identify what code is the issue.  It may be because I can't find a function in the "googlesheets4" package that allows you to write the data to the connected spreadsheet(as of now the app uses the old write functions from the old "googlesheets" package but that does not appear to be working.

**Comment by nickmerl** [comment]
get warning message "Sign in with Google temporarily disabled for this app
This app has not been verified yet by Google in order to use Google Sign In."

**Comment by merlinoa** [comment]
It ways in the googlesheets4 README.md that write functionality is not yet implemented for this package: https://github.com/tidyverse/googlesheets4/blob/master/README.md  

So for now, just work with Patrick to get the read functionality set up.  Create the table in Google sheets manually with Google Sheets, and read it into the app.

**Comment by nickmerl** [comment]
able to read in google sheet commit 1c2180df5284773b51a755ee1e0d5d699eda7c2a
